### PR TITLE
Scripts: Fix a stupid typo in the MTK branch (DISK already contains `/dev/`)

### PR DESCRIPTION
**Pull request by baskerville**
A fix based on the log posted in [this comment](https://github.com/koreader/koreader/pull/11737#issuecomment-2088415917).

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/KoboUSBMS/3)

### CODE REVIEW

**Comment by Frenzie** [comment]
That can't be true for basically all other devices though, only for those specific devices?

**Comment by Frenzie** [comment]
That is, I imagine it should be something like this:
```sh
case $DISK in
  /dev*)
    PARTITION=${DISK}0p12
    ;;
  *)
    PARTITION=/dev/${DISK}0p12
    ;;
esac
```

**Comment by benoit-pierre** [comment]
Or `PARTITION=/dev/${DISK#/dev/}0p12`.

**Comment by Frenzie** [comment]
Is parameter expansion POSIX or Bash?

**Comment by benoit-pierre** [comment]
POSIX.

**Comment by Frenzie** [comment]
Either way would be fine by me then, but I just realized I misinterpreted the diff in combination with the PR message and it's not about some exported Kobo variable:

https://github.com/koreader/KoboUSBMS/blob/f633525d9eccab34e0af9ddd6b74bb0223972afe/scripts/end-usbms.sh#L29C1-L29C5

So basically just a typo from last year, I imagine. Waiting for @NiLuJe to confirm. :-)

**Review by Frenzie — APPROVED** [review]

**Comment by NiLuJe** [comment]
Glad it turned out to be something very dumb from my part ;o).

Yep, LGTM, thanks!

**Pull request merged**
